syntax = "proto3";

package auth;

option go_package = "github.com/vikasrathod4299/microservice/proto/auth";

enum UserRole{
  USER_ROLE_UNSPECIFIED = 0;
  RIDER = 1;
  DRVIER = 2;
}
message User {
  string id = 1;
  string name = 2;
  string email = 3;
  string phone = 4;
  UserRole role = 5;
  int64 created_at = 6;
  int64 updated_at = 7;
}

message RegisterRequest {
  string name = 1;
  string phone = 2;
  string email = 3;
  string password = 4;
  UserRole role = 5;
}

message LoginRequest {
  string email = 1;
  string password = 2;
}

message AuthResponse {
  string access_token = 1;
  string token_type = 2;
  int64 expires_at = 3;
  User user = 4;
}

message GetUserRequest {
  string id = 1;
}

service AuthService {
  rpc Register(RegisterRequest) returns (AuthResponse);
  rpc Login(LoginRequest) returns (AuthResponse);
  rpc GetUser(GetUserRequest) returns (User);
}
