// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: proto/driver/driver.proto

package driver

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DriverAvailability int32

const (
	DriverAvailability_DRIVER_AVAILABILITY_UNSPECIFIED DriverAvailability = 0
	DriverAvailability_OFFLINE                         DriverAvailability = 1
	DriverAvailability_ONLINE                          DriverAvailability = 2
	DriverAvailability_ON_TRIP                         DriverAvailability = 3
)

// Enum value maps for DriverAvailability.
var (
	DriverAvailability_name = map[int32]string{
		0: "DRIVER_AVAILABILITY_UNSPECIFIED",
		1: "OFFLINE",
		2: "ONLINE",
		3: "ON_TRIP",
	}
	DriverAvailability_value = map[string]int32{
		"DRIVER_AVAILABILITY_UNSPECIFIED": 0,
		"OFFLINE":                         1,
		"ONLINE":                          2,
		"ON_TRIP":                         3,
	}
)

func (x DriverAvailability) Enum() *DriverAvailability {
	p := new(DriverAvailability)
	*p = x
	return p
}

func (x DriverAvailability) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DriverAvailability) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_driver_driver_proto_enumTypes[0].Descriptor()
}

func (DriverAvailability) Type() protoreflect.EnumType {
	return &file_proto_driver_driver_proto_enumTypes[0]
}

func (x DriverAvailability) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DriverAvailability.Descriptor instead.
func (DriverAvailability) EnumDescriptor() ([]byte, []int) {
	return file_proto_driver_driver_proto_rawDescGZIP(), []int{0}
}

type Driver struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Phone         string                 `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	VehicleMake   string                 `protobuf:"bytes,4,opt,name=vehicle_make,json=vehicleMake,proto3" json:"vehicle_make,omitempty"`
	VehicleModel  string                 `protobuf:"bytes,5,opt,name=vehicle_model,json=vehicleModel,proto3" json:"vehicle_model,omitempty"`
	LicensePlate  string                 `protobuf:"bytes,6,opt,name=license_plate,json=licensePlate,proto3" json:"license_plate,omitempty"`
	Availability  DriverAvailability     `protobuf:"varint,7,opt,name=availability,proto3,enum=driver.DriverAvailability" json:"availability,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Driver) Reset() {
	*x = Driver{}
	mi := &file_proto_driver_driver_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Driver) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Driver) ProtoMessage() {}

func (x *Driver) ProtoReflect() protoreflect.Message {
	mi := &file_proto_driver_driver_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Driver.ProtoReflect.Descriptor instead.
func (*Driver) Descriptor() ([]byte, []int) {
	return file_proto_driver_driver_proto_rawDescGZIP(), []int{0}
}

func (x *Driver) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Driver) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Driver) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *Driver) GetVehicleMake() string {
	if x != nil {
		return x.VehicleMake
	}
	return ""
}

func (x *Driver) GetVehicleModel() string {
	if x != nil {
		return x.VehicleModel
	}
	return ""
}

func (x *Driver) GetLicensePlate() string {
	if x != nil {
		return x.LicensePlate
	}
	return ""
}

func (x *Driver) GetAvailability() DriverAvailability {
	if x != nil {
		return x.Availability
	}
	return DriverAvailability_DRIVER_AVAILABILITY_UNSPECIFIED
}

type CreateDriverRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Phone         string                 `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	VehicleMake   string                 `protobuf:"bytes,3,opt,name=vehicle_make,json=vehicleMake,proto3" json:"vehicle_make,omitempty"`
	VehicleModel  string                 `protobuf:"bytes,4,opt,name=vehicle_model,json=vehicleModel,proto3" json:"vehicle_model,omitempty"`
	LicensePlate  string                 `protobuf:"bytes,5,opt,name=license_plate,json=licensePlate,proto3" json:"license_plate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDriverRequest) Reset() {
	*x = CreateDriverRequest{}
	mi := &file_proto_driver_driver_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDriverRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDriverRequest) ProtoMessage() {}

func (x *CreateDriverRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_driver_driver_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDriverRequest.ProtoReflect.Descriptor instead.
func (*CreateDriverRequest) Descriptor() ([]byte, []int) {
	return file_proto_driver_driver_proto_rawDescGZIP(), []int{1}
}

func (x *CreateDriverRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateDriverRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *CreateDriverRequest) GetVehicleMake() string {
	if x != nil {
		return x.VehicleMake
	}
	return ""
}

func (x *CreateDriverRequest) GetVehicleModel() string {
	if x != nil {
		return x.VehicleModel
	}
	return ""
}

func (x *CreateDriverRequest) GetLicensePlate() string {
	if x != nil {
		return x.LicensePlate
	}
	return ""
}

type DriverId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DriverId      string                 `protobuf:"bytes,1,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DriverId) Reset() {
	*x = DriverId{}
	mi := &file_proto_driver_driver_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriverId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverId) ProtoMessage() {}

func (x *DriverId) ProtoReflect() protoreflect.Message {
	mi := &file_proto_driver_driver_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverId.ProtoReflect.Descriptor instead.
func (*DriverId) Descriptor() ([]byte, []int) {
	return file_proto_driver_driver_proto_rawDescGZIP(), []int{2}
}

func (x *DriverId) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

type UpdateDriverAvailabilityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DriverId      string                 `protobuf:"bytes,1,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	Availability  DriverAvailability     `protobuf:"varint,2,opt,name=availability,proto3,enum=driver.DriverAvailability" json:"availability,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDriverAvailabilityRequest) Reset() {
	*x = UpdateDriverAvailabilityRequest{}
	mi := &file_proto_driver_driver_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDriverAvailabilityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDriverAvailabilityRequest) ProtoMessage() {}

func (x *UpdateDriverAvailabilityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_driver_driver_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDriverAvailabilityRequest.ProtoReflect.Descriptor instead.
func (*UpdateDriverAvailabilityRequest) Descriptor() ([]byte, []int) {
	return file_proto_driver_driver_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateDriverAvailabilityRequest) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *UpdateDriverAvailabilityRequest) GetAvailability() DriverAvailability {
	if x != nil {
		return x.Availability
	}
	return DriverAvailability_DRIVER_AVAILABILITY_UNSPECIFIED
}

type DriverResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DriverResponse) Reset() {
	*x = DriverResponse{}
	mi := &file_proto_driver_driver_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriverResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverResponse) ProtoMessage() {}

func (x *DriverResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_driver_driver_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverResponse.ProtoReflect.Descriptor instead.
func (*DriverResponse) Descriptor() ([]byte, []int) {
	return file_proto_driver_driver_proto_rawDescGZIP(), []int{4}
}

func (x *DriverResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DriverResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_driver_driver_proto protoreflect.FileDescriptor

const file_proto_driver_driver_proto_rawDesc = "" +
	"\n" +
	"\x19proto/driver/driver.proto\x12\x06driver\"\xef\x01\n" +
	"\x06Driver\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05phone\x18\x03 \x01(\tR\x05phone\x12!\n" +
	"\fvehicle_make\x18\x04 \x01(\tR\vvehicleMake\x12#\n" +
	"\rvehicle_model\x18\x05 \x01(\tR\fvehicleModel\x12#\n" +
	"\rlicense_plate\x18\x06 \x01(\tR\flicensePlate\x12>\n" +
	"\favailability\x18\a \x01(\x0e2\x1a.driver.DriverAvailabilityR\favailability\"\xac\x01\n" +
	"\x13CreateDriverRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05phone\x18\x02 \x01(\tR\x05phone\x12!\n" +
	"\fvehicle_make\x18\x03 \x01(\tR\vvehicleMake\x12#\n" +
	"\rvehicle_model\x18\x04 \x01(\tR\fvehicleModel\x12#\n" +
	"\rlicense_plate\x18\x05 \x01(\tR\flicensePlate\"'\n" +
	"\bDriverId\x12\x1b\n" +
	"\tdriver_id\x18\x01 \x01(\tR\bdriverId\"~\n" +
	"\x1fUpdateDriverAvailabilityRequest\x12\x1b\n" +
	"\tdriver_id\x18\x01 \x01(\tR\bdriverId\x12>\n" +
	"\favailability\x18\x02 \x01(\x0e2\x1a.driver.DriverAvailabilityR\favailability\"D\n" +
	"\x0eDriverResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage*_\n" +
	"\x12DriverAvailability\x12#\n" +
	"\x1fDRIVER_AVAILABILITY_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aOFFLINE\x10\x01\x12\n" +
	"\n" +
	"\x06ONLINE\x10\x02\x12\v\n" +
	"\aON_TRIP\x10\x032\xd8\x01\n" +
	"\rDriverService\x12;\n" +
	"\fCreateDriver\x12\x1b.driver.CreateDriverRequest\x1a\x0e.driver.Driver\x12-\n" +
	"\tGetDriver\x12\x10.driver.DriverId\x1a\x0e.driver.Driver\x12[\n" +
	"\x18UpdateDriverAvailability\x12'.driver.UpdateDriverAvailabilityRequest\x1a\x16.driver.DriverResponseB6Z4github.com/vikasrathod4299/microservice/proto/driverb\x06proto3"

var (
	file_proto_driver_driver_proto_rawDescOnce sync.Once
	file_proto_driver_driver_proto_rawDescData []byte
)

func file_proto_driver_driver_proto_rawDescGZIP() []byte {
	file_proto_driver_driver_proto_rawDescOnce.Do(func() {
		file_proto_driver_driver_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_driver_driver_proto_rawDesc), len(file_proto_driver_driver_proto_rawDesc)))
	})
	return file_proto_driver_driver_proto_rawDescData
}

var file_proto_driver_driver_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_driver_driver_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_driver_driver_proto_goTypes = []any{
	(DriverAvailability)(0),                 // 0: driver.DriverAvailability
	(*Driver)(nil),                          // 1: driver.Driver
	(*CreateDriverRequest)(nil),             // 2: driver.CreateDriverRequest
	(*DriverId)(nil),                        // 3: driver.DriverId
	(*UpdateDriverAvailabilityRequest)(nil), // 4: driver.UpdateDriverAvailabilityRequest
	(*DriverResponse)(nil),                  // 5: driver.DriverResponse
}
var file_proto_driver_driver_proto_depIdxs = []int32{
	0, // 0: driver.Driver.availability:type_name -> driver.DriverAvailability
	0, // 1: driver.UpdateDriverAvailabilityRequest.availability:type_name -> driver.DriverAvailability
	2, // 2: driver.DriverService.CreateDriver:input_type -> driver.CreateDriverRequest
	3, // 3: driver.DriverService.GetDriver:input_type -> driver.DriverId
	4, // 4: driver.DriverService.UpdateDriverAvailability:input_type -> driver.UpdateDriverAvailabilityRequest
	1, // 5: driver.DriverService.CreateDriver:output_type -> driver.Driver
	1, // 6: driver.DriverService.GetDriver:output_type -> driver.Driver
	5, // 7: driver.DriverService.UpdateDriverAvailability:output_type -> driver.DriverResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_driver_driver_proto_init() }
func file_proto_driver_driver_proto_init() {
	if File_proto_driver_driver_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_driver_driver_proto_rawDesc), len(file_proto_driver_driver_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_driver_driver_proto_goTypes,
		DependencyIndexes: file_proto_driver_driver_proto_depIdxs,
		EnumInfos:         file_proto_driver_driver_proto_enumTypes,
		MessageInfos:      file_proto_driver_driver_proto_msgTypes,
	}.Build()
	File_proto_driver_driver_proto = out.File
	file_proto_driver_driver_proto_goTypes = nil
	file_proto_driver_driver_proto_depIdxs = nil
}
