// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dispatchRepo

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Trip struct {
	ID         string             `json:"id"`
	RiderID    string             `json:"rider_id"`
	DriverID   pgtype.Text        `json:"driver_id"`
	Status     string             `json:"status"`
	PickupLat  float64            `json:"pickup_lat"`
	PickupLng  float64            `json:"pickup_lng"`
	DropoffLat float64            `json:"dropoff_lat"`
	DropoffLng float64            `json:"dropoff_lng"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}
