// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package dispatchRepo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTrip = `-- name: CreateTrip :one
INSERT INTO trips (
    id, rider_id, driver_id, status, pickup_lat, pickup_lng, dropoff_lat, dropoff_lng, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, NOW(), NOW()
)
RETURNING id, rider_id, driver_id, status, pickup_lat, pickup_lng, dropoff_lat, dropoff_lng, created_at, updated_at
`

type CreateTripParams struct {
	ID         string      `json:"id"`
	RiderID    string      `json:"rider_id"`
	DriverID   pgtype.Text `json:"driver_id"`
	Status     string      `json:"status"`
	PickupLat  float64     `json:"pickup_lat"`
	PickupLng  float64     `json:"pickup_lng"`
	DropoffLat float64     `json:"dropoff_lat"`
	DropoffLng float64     `json:"dropoff_lng"`
}

func (q *Queries) CreateTrip(ctx context.Context, arg CreateTripParams) (Trip, error) {
	row := q.db.QueryRow(ctx, createTrip,
		arg.ID,
		arg.RiderID,
		arg.DriverID,
		arg.Status,
		arg.PickupLat,
		arg.PickupLng,
		arg.DropoffLat,
		arg.DropoffLng,
	)
	var i Trip
	err := row.Scan(
		&i.ID,
		&i.RiderID,
		&i.DriverID,
		&i.Status,
		&i.PickupLat,
		&i.PickupLng,
		&i.DropoffLat,
		&i.DropoffLng,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTripByID = `-- name: GetTripByID :one
SELECT
    id,
    rider_id,
    driver_id,
    status,
    pickup_lat,
    pickup_lng,
    dropoff_lat,
    dropoff_lng,
    created_at,
    updated_at
FROM trips
WHERE id = $1
`

func (q *Queries) GetTripByID(ctx context.Context, id string) (Trip, error) {
	row := q.db.QueryRow(ctx, getTripByID, id)
	var i Trip
	err := row.Scan(
		&i.ID,
		&i.RiderID,
		&i.DriverID,
		&i.Status,
		&i.PickupLat,
		&i.PickupLng,
		&i.DropoffLat,
		&i.DropoffLng,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTripStatus = `-- name: UpdateTripStatus :one
UPDATE trips
SET
    status = $1,
    driver_id = COALESCE(
        NULLIF($2::text, ''),
        driver_id
    ),
    updated_at = NOW()
WHERE id = $3
RETURNING
    id,
    rider_id,
    driver_id,
    status,
    pickup_lat,
    pickup_lng,
    dropoff_lat,
    dropoff_lng,
    created_at,
    updated_at
`

type UpdateTripStatusParams struct {
	Status   string `json:"status"`
	DriverID string `json:"driver_id"`
	ID       string `json:"id"`
}

func (q *Queries) UpdateTripStatus(ctx context.Context, arg UpdateTripStatusParams) (Trip, error) {
	row := q.db.QueryRow(ctx, updateTripStatus, arg.Status, arg.DriverID, arg.ID)
	var i Trip
	err := row.Scan(
		&i.ID,
		&i.RiderID,
		&i.DriverID,
		&i.Status,
		&i.PickupLat,
		&i.PickupLng,
		&i.DropoffLat,
		&i.DropoffLng,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
