// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dispatchRepo

import (
	"context"
)

type Querier interface {
	CreateTrip(ctx context.Context, arg CreateTripParams) (Trip, error)
	GetTripByID(ctx context.Context, id string) (Trip, error)
	UpdateTripStatus(ctx context.Context, arg UpdateTripStatusParams) (Trip, error)
}

var _ Querier = (*Queries)(nil)
