// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: proto/dispatch/dispatch.proto

package dispatch

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TripStatus int32

const (
	TripStatus_TRIP_STATUS_UNSPECIFIED TripStatus = 0
	TripStatus_SEARCHING               TripStatus = 1
	TripStatus_DRIVER_ASSIGNED         TripStatus = 2
	TripStatus_DRIVER_ARRIVED          TripStatus = 3
	TripStatus_IN_TRANSIT              TripStatus = 4
	TripStatus_COMPLETED               TripStatus = 5
	TripStatus_CANCELED                TripStatus = 6
)

// Enum value maps for TripStatus.
var (
	TripStatus_name = map[int32]string{
		0: "TRIP_STATUS_UNSPECIFIED",
		1: "SEARCHING",
		2: "DRIVER_ASSIGNED",
		3: "DRIVER_ARRIVED",
		4: "IN_TRANSIT",
		5: "COMPLETED",
		6: "CANCELED",
	}
	TripStatus_value = map[string]int32{
		"TRIP_STATUS_UNSPECIFIED": 0,
		"SEARCHING":               1,
		"DRIVER_ASSIGNED":         2,
		"DRIVER_ARRIVED":          3,
		"IN_TRANSIT":              4,
		"COMPLETED":               5,
		"CANCELED":                6,
	}
)

func (x TripStatus) Enum() *TripStatus {
	p := new(TripStatus)
	*p = x
	return p
}

func (x TripStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TripStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_dispatch_dispatch_proto_enumTypes[0].Descriptor()
}

func (TripStatus) Type() protoreflect.EnumType {
	return &file_proto_dispatch_dispatch_proto_enumTypes[0]
}

func (x TripStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TripStatus.Descriptor instead.
func (TripStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_dispatch_dispatch_proto_rawDescGZIP(), []int{0}
}

type TripRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RiderId       string                 `protobuf:"bytes,1,opt,name=rider_id,json=riderId,proto3" json:"rider_id,omitempty"`
	PickupLat     float64                `protobuf:"fixed64,2,opt,name=pickup_lat,json=pickupLat,proto3" json:"pickup_lat,omitempty"`
	PickupLng     float64                `protobuf:"fixed64,3,opt,name=pickup_lng,json=pickupLng,proto3" json:"pickup_lng,omitempty"`
	DropoffLat    float64                `protobuf:"fixed64,4,opt,name=dropoff_lat,json=dropoffLat,proto3" json:"dropoff_lat,omitempty"`
	DropoffLng    float64                `protobuf:"fixed64,5,opt,name=dropoff_lng,json=dropoffLng,proto3" json:"dropoff_lng,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TripRequest) Reset() {
	*x = TripRequest{}
	mi := &file_proto_dispatch_dispatch_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TripRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TripRequest) ProtoMessage() {}

func (x *TripRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dispatch_dispatch_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TripRequest.ProtoReflect.Descriptor instead.
func (*TripRequest) Descriptor() ([]byte, []int) {
	return file_proto_dispatch_dispatch_proto_rawDescGZIP(), []int{0}
}

func (x *TripRequest) GetRiderId() string {
	if x != nil {
		return x.RiderId
	}
	return ""
}

func (x *TripRequest) GetPickupLat() float64 {
	if x != nil {
		return x.PickupLat
	}
	return 0
}

func (x *TripRequest) GetPickupLng() float64 {
	if x != nil {
		return x.PickupLng
	}
	return 0
}

func (x *TripRequest) GetDropoffLat() float64 {
	if x != nil {
		return x.DropoffLat
	}
	return 0
}

func (x *TripRequest) GetDropoffLng() float64 {
	if x != nil {
		return x.DropoffLng
	}
	return 0
}

type Trip struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TripId        string                 `protobuf:"bytes,1,opt,name=trip_id,json=tripId,proto3" json:"trip_id,omitempty"`
	RiderId       string                 `protobuf:"bytes,2,opt,name=rider_id,json=riderId,proto3" json:"rider_id,omitempty"`
	DriverId      string                 `protobuf:"bytes,3,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	Status        TripStatus             `protobuf:"varint,4,opt,name=status,proto3,enum=dispatch.TripStatus" json:"status,omitempty"`
	PickupLat     float64                `protobuf:"fixed64,5,opt,name=pickup_lat,json=pickupLat,proto3" json:"pickup_lat,omitempty"`
	PickupLng     float64                `protobuf:"fixed64,6,opt,name=pickup_lng,json=pickupLng,proto3" json:"pickup_lng,omitempty"`
	DropoffLat    float64                `protobuf:"fixed64,7,opt,name=dropoff_lat,json=dropoffLat,proto3" json:"dropoff_lat,omitempty"`
	DropoffLng    float64                `protobuf:"fixed64,8,opt,name=dropoff_lng,json=dropoffLng,proto3" json:"dropoff_lng,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Trip) Reset() {
	*x = Trip{}
	mi := &file_proto_dispatch_dispatch_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Trip) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Trip) ProtoMessage() {}

func (x *Trip) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dispatch_dispatch_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Trip.ProtoReflect.Descriptor instead.
func (*Trip) Descriptor() ([]byte, []int) {
	return file_proto_dispatch_dispatch_proto_rawDescGZIP(), []int{1}
}

func (x *Trip) GetTripId() string {
	if x != nil {
		return x.TripId
	}
	return ""
}

func (x *Trip) GetRiderId() string {
	if x != nil {
		return x.RiderId
	}
	return ""
}

func (x *Trip) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *Trip) GetStatus() TripStatus {
	if x != nil {
		return x.Status
	}
	return TripStatus_TRIP_STATUS_UNSPECIFIED
}

func (x *Trip) GetPickupLat() float64 {
	if x != nil {
		return x.PickupLat
	}
	return 0
}

func (x *Trip) GetPickupLng() float64 {
	if x != nil {
		return x.PickupLng
	}
	return 0
}

func (x *Trip) GetDropoffLat() float64 {
	if x != nil {
		return x.DropoffLat
	}
	return 0
}

func (x *Trip) GetDropoffLng() float64 {
	if x != nil {
		return x.DropoffLng
	}
	return 0
}

func (x *Trip) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Trip) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type TripId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TripId        string                 `protobuf:"bytes,1,opt,name=trip_id,json=tripId,proto3" json:"trip_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TripId) Reset() {
	*x = TripId{}
	mi := &file_proto_dispatch_dispatch_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TripId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TripId) ProtoMessage() {}

func (x *TripId) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dispatch_dispatch_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TripId.ProtoReflect.Descriptor instead.
func (*TripId) Descriptor() ([]byte, []int) {
	return file_proto_dispatch_dispatch_proto_rawDescGZIP(), []int{2}
}

func (x *TripId) GetTripId() string {
	if x != nil {
		return x.TripId
	}
	return ""
}

type UpdateTripStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TripId        string                 `protobuf:"bytes,1,opt,name=trip_id,json=tripId,proto3" json:"trip_id,omitempty"`
	Status        TripStatus             `protobuf:"varint,2,opt,name=status,proto3,enum=dispatch.TripStatus" json:"status,omitempty"`
	DriverId      string                 `protobuf:"bytes,3,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTripStatusRequest) Reset() {
	*x = UpdateTripStatusRequest{}
	mi := &file_proto_dispatch_dispatch_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTripStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTripStatusRequest) ProtoMessage() {}

func (x *UpdateTripStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dispatch_dispatch_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTripStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateTripStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_dispatch_dispatch_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateTripStatusRequest) GetTripId() string {
	if x != nil {
		return x.TripId
	}
	return ""
}

func (x *UpdateTripStatusRequest) GetStatus() TripStatus {
	if x != nil {
		return x.Status
	}
	return TripStatus_TRIP_STATUS_UNSPECIFIED
}

func (x *UpdateTripStatusRequest) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

var File_proto_dispatch_dispatch_proto protoreflect.FileDescriptor

const file_proto_dispatch_dispatch_proto_rawDesc = "" +
	"\n" +
	"\x1dproto/dispatch/dispatch.proto\x12\bdispatch\"\xa8\x01\n" +
	"\vTripRequest\x12\x19\n" +
	"\brider_id\x18\x01 \x01(\tR\ariderId\x12\x1d\n" +
	"\n" +
	"pickup_lat\x18\x02 \x01(\x01R\tpickupLat\x12\x1d\n" +
	"\n" +
	"pickup_lng\x18\x03 \x01(\x01R\tpickupLng\x12\x1f\n" +
	"\vdropoff_lat\x18\x04 \x01(\x01R\n" +
	"dropoffLat\x12\x1f\n" +
	"\vdropoff_lng\x18\x05 \x01(\x01R\n" +
	"dropoffLng\"\xc3\x02\n" +
	"\x04Trip\x12\x17\n" +
	"\atrip_id\x18\x01 \x01(\tR\x06tripId\x12\x19\n" +
	"\brider_id\x18\x02 \x01(\tR\ariderId\x12\x1b\n" +
	"\tdriver_id\x18\x03 \x01(\tR\bdriverId\x12,\n" +
	"\x06status\x18\x04 \x01(\x0e2\x14.dispatch.TripStatusR\x06status\x12\x1d\n" +
	"\n" +
	"pickup_lat\x18\x05 \x01(\x01R\tpickupLat\x12\x1d\n" +
	"\n" +
	"pickup_lng\x18\x06 \x01(\x01R\tpickupLng\x12\x1f\n" +
	"\vdropoff_lat\x18\a \x01(\x01R\n" +
	"dropoffLat\x12\x1f\n" +
	"\vdropoff_lng\x18\b \x01(\x01R\n" +
	"dropoffLng\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\x03R\tupdatedAt\"!\n" +
	"\x06TripId\x12\x17\n" +
	"\atrip_id\x18\x01 \x01(\tR\x06tripId\"}\n" +
	"\x17UpdateTripStatusRequest\x12\x17\n" +
	"\atrip_id\x18\x01 \x01(\tR\x06tripId\x12,\n" +
	"\x06status\x18\x02 \x01(\x0e2\x14.dispatch.TripStatusR\x06status\x12\x1b\n" +
	"\tdriver_id\x18\x03 \x01(\tR\bdriverId*\x8e\x01\n" +
	"\n" +
	"TripStatus\x12\x1b\n" +
	"\x17TRIP_STATUS_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tSEARCHING\x10\x01\x12\x13\n" +
	"\x0fDRIVER_ASSIGNED\x10\x02\x12\x12\n" +
	"\x0eDRIVER_ARRIVED\x10\x03\x12\x0e\n" +
	"\n" +
	"IN_TRANSIT\x10\x04\x12\r\n" +
	"\tCOMPLETED\x10\x05\x12\f\n" +
	"\bCANCELED\x10\x062\xbb\x01\n" +
	"\x0fDispatchService\x124\n" +
	"\vRequestTrip\x12\x15.dispatch.TripRequest\x1a\x0e.dispatch.Trip\x12+\n" +
	"\aGetTrip\x12\x10.dispatch.TripId\x1a\x0e.dispatch.Trip\x12E\n" +
	"\x10UpdateTripStatus\x12!.dispatch.UpdateTripStatusRequest\x1a\x0e.dispatch.TripB8Z6github.com/vikasrathod4299/microservice/proto/dispatchb\x06proto3"

var (
	file_proto_dispatch_dispatch_proto_rawDescOnce sync.Once
	file_proto_dispatch_dispatch_proto_rawDescData []byte
)

func file_proto_dispatch_dispatch_proto_rawDescGZIP() []byte {
	file_proto_dispatch_dispatch_proto_rawDescOnce.Do(func() {
		file_proto_dispatch_dispatch_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_dispatch_dispatch_proto_rawDesc), len(file_proto_dispatch_dispatch_proto_rawDesc)))
	})
	return file_proto_dispatch_dispatch_proto_rawDescData
}

var file_proto_dispatch_dispatch_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_dispatch_dispatch_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_dispatch_dispatch_proto_goTypes = []any{
	(TripStatus)(0),                 // 0: dispatch.TripStatus
	(*TripRequest)(nil),             // 1: dispatch.TripRequest
	(*Trip)(nil),                    // 2: dispatch.Trip
	(*TripId)(nil),                  // 3: dispatch.TripId
	(*UpdateTripStatusRequest)(nil), // 4: dispatch.UpdateTripStatusRequest
}
var file_proto_dispatch_dispatch_proto_depIdxs = []int32{
	0, // 0: dispatch.Trip.status:type_name -> dispatch.TripStatus
	0, // 1: dispatch.UpdateTripStatusRequest.status:type_name -> dispatch.TripStatus
	1, // 2: dispatch.DispatchService.RequestTrip:input_type -> dispatch.TripRequest
	3, // 3: dispatch.DispatchService.GetTrip:input_type -> dispatch.TripId
	4, // 4: dispatch.DispatchService.UpdateTripStatus:input_type -> dispatch.UpdateTripStatusRequest
	2, // 5: dispatch.DispatchService.RequestTrip:output_type -> dispatch.Trip
	2, // 6: dispatch.DispatchService.GetTrip:output_type -> dispatch.Trip
	2, // 7: dispatch.DispatchService.UpdateTripStatus:output_type -> dispatch.Trip
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_dispatch_dispatch_proto_init() }
func file_proto_dispatch_dispatch_proto_init() {
	if File_proto_dispatch_dispatch_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_dispatch_dispatch_proto_rawDesc), len(file_proto_dispatch_dispatch_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_dispatch_dispatch_proto_goTypes,
		DependencyIndexes: file_proto_dispatch_dispatch_proto_depIdxs,
		EnumInfos:         file_proto_dispatch_dispatch_proto_enumTypes,
		MessageInfos:      file_proto_dispatch_dispatch_proto_msgTypes,
	}.Build()
	File_proto_dispatch_dispatch_proto = out.File
	file_proto_dispatch_dispatch_proto_goTypes = nil
	file_proto_dispatch_dispatch_proto_depIdxs = nil
}
