// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: proto/location/location.proto

package location

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A single GPS ping from a driver's phone
type DriverLocation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DriverId      string                 `protobuf:"bytes,1,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	Latitude      float64                `protobuf:"fixed64,2,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,3,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DriverLocation) Reset() {
	*x = DriverLocation{}
	mi := &file_proto_location_location_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriverLocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverLocation) ProtoMessage() {}

func (x *DriverLocation) ProtoReflect() protoreflect.Message {
	mi := &file_proto_location_location_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverLocation.ProtoReflect.Descriptor instead.
func (*DriverLocation) Descriptor() ([]byte, []int) {
	return file_proto_location_location_proto_rawDescGZIP(), []int{0}
}

func (x *DriverLocation) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *DriverLocation) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *DriverLocation) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *DriverLocation) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// Request: "find drivers near this point"
type NearbyDriversRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Latitude      float64                `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	RadiusKm      float64                `protobuf:"fixed64,3,opt,name=radius_km,json=radiusKm,proto3" json:"radius_km,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NearbyDriversRequest) Reset() {
	*x = NearbyDriversRequest{}
	mi := &file_proto_location_location_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NearbyDriversRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NearbyDriversRequest) ProtoMessage() {}

func (x *NearbyDriversRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_location_location_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NearbyDriversRequest.ProtoReflect.Descriptor instead.
func (*NearbyDriversRequest) Descriptor() ([]byte, []int) {
	return file_proto_location_location_proto_rawDescGZIP(), []int{1}
}

func (x *NearbyDriversRequest) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *NearbyDriversRequest) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *NearbyDriversRequest) GetRadiusKm() float64 {
	if x != nil {
		return x.RadiusKm
	}
	return 0
}

func (x *NearbyDriversRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// Response: list of nearby drivers with their distance
type NearbyDriversResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Drivers       []*NearbyDriver        `protobuf:"bytes,1,rep,name=drivers,proto3" json:"drivers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NearbyDriversResponse) Reset() {
	*x = NearbyDriversResponse{}
	mi := &file_proto_location_location_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NearbyDriversResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NearbyDriversResponse) ProtoMessage() {}

func (x *NearbyDriversResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_location_location_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NearbyDriversResponse.ProtoReflect.Descriptor instead.
func (*NearbyDriversResponse) Descriptor() ([]byte, []int) {
	return file_proto_location_location_proto_rawDescGZIP(), []int{2}
}

func (x *NearbyDriversResponse) GetDrivers() []*NearbyDriver {
	if x != nil {
		return x.Drivers
	}
	return nil
}

type NearbyDriver struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DriverId      string                 `protobuf:"bytes,1,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	Latitude      float64                `protobuf:"fixed64,2,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,3,opt,name=longitude,proto3" json:"longitude,omitempty"`
	DistanceKm    float64                `protobuf:"fixed64,4,opt,name=distance_km,json=distanceKm,proto3" json:"distance_km,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NearbyDriver) Reset() {
	*x = NearbyDriver{}
	mi := &file_proto_location_location_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NearbyDriver) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NearbyDriver) ProtoMessage() {}

func (x *NearbyDriver) ProtoReflect() protoreflect.Message {
	mi := &file_proto_location_location_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NearbyDriver.ProtoReflect.Descriptor instead.
func (*NearbyDriver) Descriptor() ([]byte, []int) {
	return file_proto_location_location_proto_rawDescGZIP(), []int{3}
}

func (x *NearbyDriver) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *NearbyDriver) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *NearbyDriver) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *NearbyDriver) GetDistanceKm() float64 {
	if x != nil {
		return x.DistanceKm
	}
	return 0
}

// Used for removing a driver from the geo-index
type DriverID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DriverId      string                 `protobuf:"bytes,1,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DriverID) Reset() {
	*x = DriverID{}
	mi := &file_proto_location_location_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriverID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverID) ProtoMessage() {}

func (x *DriverID) ProtoReflect() protoreflect.Message {
	mi := &file_proto_location_location_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverID.ProtoReflect.Descriptor instead.
func (*DriverID) Descriptor() ([]byte, []int) {
	return file_proto_location_location_proto_rawDescGZIP(), []int{4}
}

func (x *DriverID) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

// Generic response
type LocationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocationResponse) Reset() {
	*x = LocationResponse{}
	mi := &file_proto_location_location_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocationResponse) ProtoMessage() {}

func (x *LocationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_location_location_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocationResponse.ProtoReflect.Descriptor instead.
func (*LocationResponse) Descriptor() ([]byte, []int) {
	return file_proto_location_location_proto_rawDescGZIP(), []int{5}
}

func (x *LocationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *LocationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_location_location_proto protoreflect.FileDescriptor

const file_proto_location_location_proto_rawDesc = "" +
	"\n" +
	"\x1dproto/location/location.proto\x12\blocation\"\x85\x01\n" +
	"\x0eDriverLocation\x12\x1b\n" +
	"\tdriver_id\x18\x01 \x01(\tR\bdriverId\x12\x1a\n" +
	"\blatitude\x18\x02 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x03 \x01(\x01R\tlongitude\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\"\x83\x01\n" +
	"\x14NearbyDriversRequest\x12\x1a\n" +
	"\blatitude\x18\x01 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x02 \x01(\x01R\tlongitude\x12\x1b\n" +
	"\tradius_km\x18\x03 \x01(\x01R\bradiusKm\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\"I\n" +
	"\x15NearbyDriversResponse\x120\n" +
	"\adrivers\x18\x01 \x03(\v2\x16.location.NearbyDriverR\adrivers\"\x86\x01\n" +
	"\fNearbyDriver\x12\x1b\n" +
	"\tdriver_id\x18\x01 \x01(\tR\bdriverId\x12\x1a\n" +
	"\blatitude\x18\x02 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x03 \x01(\x01R\tlongitude\x12\x1f\n" +
	"\vdistance_km\x18\x04 \x01(\x01R\n" +
	"distanceKm\"'\n" +
	"\bDriverID\x12\x1b\n" +
	"\tdriver_id\x18\x01 \x01(\tR\bdriverId\"F\n" +
	"\x10LocationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xf7\x01\n" +
	"\x0fLocationService\x12N\n" +
	"\x14StreamDriverLocation\x12\x18.location.DriverLocation\x1a\x1a.location.LocationResponse(\x01\x12T\n" +
	"\x11FindNearbyDrivers\x12\x1e.location.NearbyDriversRequest\x1a\x1f.location.NearbyDriversResponse\x12>\n" +
	"\fRemoveDriver\x12\x12.location.DriverID\x1a\x1a.location.LocationResponseB8Z6github.com/vikasrathod4299/microservice/proto/locationb\x06proto3"

var (
	file_proto_location_location_proto_rawDescOnce sync.Once
	file_proto_location_location_proto_rawDescData []byte
)

func file_proto_location_location_proto_rawDescGZIP() []byte {
	file_proto_location_location_proto_rawDescOnce.Do(func() {
		file_proto_location_location_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_location_location_proto_rawDesc), len(file_proto_location_location_proto_rawDesc)))
	})
	return file_proto_location_location_proto_rawDescData
}

var file_proto_location_location_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_location_location_proto_goTypes = []any{
	(*DriverLocation)(nil),        // 0: location.DriverLocation
	(*NearbyDriversRequest)(nil),  // 1: location.NearbyDriversRequest
	(*NearbyDriversResponse)(nil), // 2: location.NearbyDriversResponse
	(*NearbyDriver)(nil),          // 3: location.NearbyDriver
	(*DriverID)(nil),              // 4: location.DriverID
	(*LocationResponse)(nil),      // 5: location.LocationResponse
}
var file_proto_location_location_proto_depIdxs = []int32{
	3, // 0: location.NearbyDriversResponse.drivers:type_name -> location.NearbyDriver
	0, // 1: location.LocationService.StreamDriverLocation:input_type -> location.DriverLocation
	1, // 2: location.LocationService.FindNearbyDrivers:input_type -> location.NearbyDriversRequest
	4, // 3: location.LocationService.RemoveDriver:input_type -> location.DriverID
	5, // 4: location.LocationService.StreamDriverLocation:output_type -> location.LocationResponse
	2, // 5: location.LocationService.FindNearbyDrivers:output_type -> location.NearbyDriversResponse
	5, // 6: location.LocationService.RemoveDriver:output_type -> location.LocationResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_location_location_proto_init() }
func file_proto_location_location_proto_init() {
	if File_proto_location_location_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_location_location_proto_rawDesc), len(file_proto_location_location_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_location_location_proto_goTypes,
		DependencyIndexes: file_proto_location_location_proto_depIdxs,
		MessageInfos:      file_proto_location_location_proto_msgTypes,
	}.Build()
	File_proto_location_location_proto = out.File
	file_proto_location_location_proto_goTypes = nil
	file_proto_location_location_proto_depIdxs = nil
}
