// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: proto/location/location.proto

package location

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LocationService_StreamDriverLocation_FullMethodName = "/location.LocationService/StreamDriverLocation"
	LocationService_FindNearbyDrivers_FullMethodName    = "/location.LocationService/FindNearbyDrivers"
	LocationService_RemoveDriver_FullMethodName         = "/location.LocationService/RemoveDriver"
)

// LocationServiceClient is the client API for LocationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LocationServiceClient interface {
	StreamDriverLocation(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[DriverLocation, LocationResponse], error)
	FindNearbyDrivers(ctx context.Context, in *NearbyDriversRequest, opts ...grpc.CallOption) (*NearbyDriversResponse, error)
	RemoveDriver(ctx context.Context, in *DriverID, opts ...grpc.CallOption) (*LocationResponse, error)
}

type locationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLocationServiceClient(cc grpc.ClientConnInterface) LocationServiceClient {
	return &locationServiceClient{cc}
}

func (c *locationServiceClient) StreamDriverLocation(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[DriverLocation, LocationResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &LocationService_ServiceDesc.Streams[0], LocationService_StreamDriverLocation_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DriverLocation, LocationResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LocationService_StreamDriverLocationClient = grpc.ClientStreamingClient[DriverLocation, LocationResponse]

func (c *locationServiceClient) FindNearbyDrivers(ctx context.Context, in *NearbyDriversRequest, opts ...grpc.CallOption) (*NearbyDriversResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NearbyDriversResponse)
	err := c.cc.Invoke(ctx, LocationService_FindNearbyDrivers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *locationServiceClient) RemoveDriver(ctx context.Context, in *DriverID, opts ...grpc.CallOption) (*LocationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LocationResponse)
	err := c.cc.Invoke(ctx, LocationService_RemoveDriver_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LocationServiceServer is the server API for LocationService service.
// All implementations must embed UnimplementedLocationServiceServer
// for forward compatibility.
type LocationServiceServer interface {
	StreamDriverLocation(grpc.ClientStreamingServer[DriverLocation, LocationResponse]) error
	FindNearbyDrivers(context.Context, *NearbyDriversRequest) (*NearbyDriversResponse, error)
	RemoveDriver(context.Context, *DriverID) (*LocationResponse, error)
	mustEmbedUnimplementedLocationServiceServer()
}

// UnimplementedLocationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLocationServiceServer struct{}

func (UnimplementedLocationServiceServer) StreamDriverLocation(grpc.ClientStreamingServer[DriverLocation, LocationResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamDriverLocation not implemented")
}
func (UnimplementedLocationServiceServer) FindNearbyDrivers(context.Context, *NearbyDriversRequest) (*NearbyDriversResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FindNearbyDrivers not implemented")
}
func (UnimplementedLocationServiceServer) RemoveDriver(context.Context, *DriverID) (*LocationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveDriver not implemented")
}
func (UnimplementedLocationServiceServer) mustEmbedUnimplementedLocationServiceServer() {}
func (UnimplementedLocationServiceServer) testEmbeddedByValue()                         {}

// UnsafeLocationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LocationServiceServer will
// result in compilation errors.
type UnsafeLocationServiceServer interface {
	mustEmbedUnimplementedLocationServiceServer()
}

func RegisterLocationServiceServer(s grpc.ServiceRegistrar, srv LocationServiceServer) {
	// If the following call panics, it indicates UnimplementedLocationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LocationService_ServiceDesc, srv)
}

func _LocationService_StreamDriverLocation_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(LocationServiceServer).StreamDriverLocation(&grpc.GenericServerStream[DriverLocation, LocationResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LocationService_StreamDriverLocationServer = grpc.ClientStreamingServer[DriverLocation, LocationResponse]

func _LocationService_FindNearbyDrivers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NearbyDriversRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocationServiceServer).FindNearbyDrivers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LocationService_FindNearbyDrivers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocationServiceServer).FindNearbyDrivers(ctx, req.(*NearbyDriversRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LocationService_RemoveDriver_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DriverID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocationServiceServer).RemoveDriver(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LocationService_RemoveDriver_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocationServiceServer).RemoveDriver(ctx, req.(*DriverID))
	}
	return interceptor(ctx, in, info, handler)
}

// LocationService_ServiceDesc is the grpc.ServiceDesc for LocationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LocationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "location.LocationService",
	HandlerType: (*LocationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FindNearbyDrivers",
			Handler:    _LocationService_FindNearbyDrivers_Handler,
		},
		{
			MethodName: "RemoveDriver",
			Handler:    _LocationService_RemoveDriver_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamDriverLocation",
			Handler:       _LocationService_StreamDriverLocation_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "proto/location/location.proto",
}
